version: "3.2"
services:
  postgres:
    image: postgres:13-alpine
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
    - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: